name: heckqm
channels:
  - conda-forge
  - defaults
dependencies:
  - ase=3.22.1
  - ipython=7.29.0
  - lightgbm=3.1.1
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - numpy=1.21.4
  - openbabel=3.1.1
  - optuna=2.5.0
  - pandas=1.3.4
  - python=3.9.1
  - rdkit=2021.09.2
  - requests=2.27.1
  - scikit-learn=1.0.1
  - submitit=1.2.1
  - threadpoolctl=3.0.0
  - tqdm=4.62.3
  - py3dmol
